version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=tinklabs
    ports:
      - "5432:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data
      - ./sql:/sql
    logging:
      driver: none
  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    links:
      - db:postgres
    volumes:
      - ./.pgadmin:/root/.pgadmin
    logging:
      driver: none
  web:
    image: node:6
    volumes:
      - .:/app
    ports:
      - "3030:3030"
    working_dir: /app
    command: npm run coverage
    depends_on:
      - db
